### ISSUE TITLE
is this work ? 

### ISSUE THREAD

**Issue by navotera** [Vitaliy-1/docxToJats#1]
Do you have any known issue for this code ?
Since I am planning to create gui for this 

Thank

**Comment by Vitaliy-1** [comment]
Hi @navotera,

Do you mean to wrap into OJS plugin? No need, it's here: https://github.com/Vitaliy-1/docxConverter
All major work that is left on the plugin, is to refresh the editor's page after conversion is done. I'm planning to start the work on it again in near time.

**Comment by navotera** [comment]
Great thank you so much Vitaliy 😊
