### ISSUE TITLE
Reference issue

### ISSUE THREAD

**Issue by waqas1223** [Vitaliy-1/docxToJats#24]
Hi vitaliy that plugin DOCX2JATS is working prefect but i am facing a issue is in refernce.
in cmd command show reffernce list is added but cant display on journal.
i doall your instructin
refernce tag haeading 
AMA stlye
Cite from mendeley
[Article1.docx](https://github.com/Vitaliy-1/DOCX2JATS/files/6646506/Article1.docx)

**Comment by Vitaliy-1** [comment]
@waqas1223,

I've transferred this issue.
The example document indeed has Mendeley tags but they are not inside the main document part but in a separate file: `/word/webextensions/webextension1.xml` with a content-type: `application/vnd.ms-office.webextension+xml`. I'm encountering it for the first time. 
Can you specify what MS Office version (release number, desktop/online...) are you using and the Mendeley version? I can take a look this weekend and add support.

**Comment by waqas1223** [comment]
hi there .
i encounter some php error. what i do
1. make article with zotero cit
2. install php 7.3
3. install git bash
4. execute command and getting this.
![Screenshot_1](https://user-images.githubusercontent.com/84614100/122230200-d9f38000-ced2-11eb-9be1-e02cc641cedd.jpg)
[Article5.docx](https://github.com/Vitaliy-1/docxToJats/files/6663471/Article5.docx)

**Comment by Vitaliy-1** [comment]
Hi @waqas1223,

According to your example you didn't specified output path, e.g.:
```
PHP docxToJats.php /mydir/Article5.docx /mydir/output/
```
(the dir should exist)

**Comment by waqas1223** [comment]
hi there i make dir but again some error counter can you write 1st to last step command with comment thanks
![Screenshot_2](https://user-images.githubusercontent.com/84614100/122328795-b4ee2400-cf49-11eb-887b-cdb575c0fef6.jpg)

**Comment by waqas1223** [comment]
hi there i resolve the issue. And the file is converted into xml file and reference tag is also added by using the absolute path. but i facing
![Screenshot_4](https://user-images.githubusercontent.com/84614100/122373229-c0a60e80-cf7a-11eb-8dae-1187d36e3d9f.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/84614100/122373245-c3086880-cf7a-11eb-8856-ad1667865847.jpg)
 the issue in  pmc validator and style checker  let me resolve this then i will connect with you.
thanks for giving the time.

**Comment by Vitaliy-1** [comment]
> hi there i make dir but again some error counter can you write 1st to last step command with comment thanks

the output folder isn't created and permission is denied to create a new one

> the issue in pmc validator and style checker let me resolve this then i will connect with you.

I don't understand the validation message. PMC validator doesn't allow nested sections?

**Comment by waqas1223** [comment]
let me solve this then i ill tell you what is problem.

**Comment by waqas1223** [comment]
hi @Vitaliy-1  sorry for late response i try to solved the error as much i can first is  your xml table conversion is cant validate in PMC XML Validator (due to p tag)  so i convert all table through  http://www.jatsxmlgenerator.com/ and replace with error table worked fine .
and last error in the reference error  tag which i cant solve it 
sir i want to send a file which is completely validate by Pmc xml validator and style checker kindly look at it if any changing possible from this file.(your email cant attached file here)
![Screenshot_2](https://user-images.githubusercontent.com/84614100/122955447-8df47f80-d399-11eb-8da4-d3ef5df7a8d1.jpg)

**Comment by Vitaliy-1** [comment]
Hi @waqas1223,

Can you explain in more details which elements are not valid or send an example of non-valid JATS XML generated by a plugin? The plugin produces XML according to Journal Publishing Tag Set v. 1.2: https://jats.nlm.nih.gov/publishing/tag-library/1.2/index.html. I don't understand by a screenshot what is wrong.

**Comment by waqas1223** [comment]
hi sorry for late reply 
i use this command line version  https://github.com/Vitaliy-1/docxToJats which create xml file base on docx file with zotero reference. The file is perfect but has some i facing some  issue.
1. First issue is this convertor create table with <p> tag which cant validate on https://www.ncbi.nlm.nih.gov/pmc/tools/xmlchecker/
2. second issue is in reference at the end of file which i already attach the screen shot.
note : the first issue i resolved by this website http://www.jatsxmlgenerator.com/ create the table in website and replace in xml file which already created by command line version.
can you tell  a complete procedure for perfect xml file can validate on PMC . i try many things but cant succeed yet.

**Comment by waqas1223** [comment]
and sir what this error means?
![Screenshot_3](https://user-images.githubusercontent.com/84614100/123317404-6a6f3780-d547-11eb-86be-59b98b6fbec0.jpg)

**Comment by waqas1223** [comment]
hi @Vitaliy-1  can you elaborate above error?

**Comment by waqas1223** [comment]
HI @Vitaliy-1  finally i resolve the all error.
but one more things this command line version  https://github.com/Vitaliy-1/docxToJats use the dtd 1.2 while there is 3.0 dtd  available. did you plan to upgrade this plugging in future.

**Comment by Vitaliy-1** [comment]
Do you mean 1.3? I'll consider it when this version becomes official.

**Comment by waqas1223** [comment]
<?xml version="1.0"?>

<!DOCTYPE article SYSTEM "journalpublishing.dtd" PUBLIC "-//NLM//DTD Journal Publishing DTD v2.3 20070202//EN">

<article xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:xlink="http://www.w3.org/1999/xlink" article-type="research-article">
in this dtd i try to embed your table (xml convertor doxToJats) then its give validations error on <p> tag in table.
while in DTD v2.3 table tags are like this.
-<table-wrap id="T1" position="float">

<label>Table-I</label>
-<caption>
<p>Patients demographic datas.</p>
</caption>
-<table width="100%" rules="groups" frame="hsides">
-<thead>
-<tr>
<th rowspan="3" align="center"/>
<th align="center" colspan="2">Group 1 (n=27) HP+TENS+US</th>
<th align="center" colspan="2">Group 2 (n=27) HP+HILT</th>
<th rowspan="3" align="center">P value</th>
</tr>
<tr>
<th align="center" colspan="4"/>
</tr>
-<tr>
<th align="center">Mean±SD</th>
<th align="center">Min-Max</th>
<th align="center">Mean±SD</th>
<th align="center">Min-Max</th>
</tr>

**Comment by waqas1223** [comment]
DOCTYPE article SYSTEM "journalpublishing.dtd" PUBLIC "-//NLM//DTD Journal Publishing DTD v2.3 20070202//EN">
article xmlns:mml="http://www.w3.org/1998/Math/MathML" xmlns:xlink="http://www.w3.org/1999/xlink" article-type="research-article">

in this dtd i try to embed your table (xml convertor doxToJats) then its give validations error on
tag in table. while in DTD v2.3 table tags are like this. -
 tr>
th rowspan="3" align="center"/>
th align="center" colspan="2">Group 1 (n=27) HP+TENS+US</th
<th align="center" colspan="2">Group 2 (n=27) HP+HILT</th
<th rowspan="3" align="center">P value</th
